# Generated by Django 4.2.4 on 2023-08-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("address", models.CharField(max_length=300)),
                ("description", models.CharField(max_length=300)),
                ("latitude", models.IntegerField(null=True)),
                ("longitude", models.IntegerField(null=True)),
                ("start_day", models.DateField(null=True)),
                ("close_day", models.DateField(null=True)),
                ("temperature", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
