# Generated by Django 4.2.4 on 2023-09-12 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name_plural": "Activities"},
        ),
    ]
