# Generated by Django 4.2.4 on 2023-08-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=280)),
                (
                    "description",
                    models.CharField(blank=True, max_length=350, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Cosmetics", "cosmetic"),
                            ("Clothes", "clothes"),
                            ("Groceries", "grocery"),
                            ("Others", "other"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
